#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ibus-unikey
Version  : 0.6.1
Release  : 1
URL      : https://github.com/vn-input/ibus-unikey/archive/0.6.1.tar.gz
Source0  : https://github.com/vn-input/ibus-unikey/archive/0.6.1.tar.gz
Summary  : IBus module for Vietnamese Keyboard
Group    : Development/Tools
License  : GPL-3.0 LGPL-2.0
Requires: ibus-unikey-data = %{version}-%{release}
Requires: ibus-unikey-libexec = %{version}-%{release}
Requires: ibus-unikey-license = %{version}-%{release}
Requires: ibus-unikey-locales = %{version}-%{release}
BuildRequires : gettext
BuildRequires : gtk+-dev
BuildRequires : intltool
BuildRequires : intltool-dev
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(ibus-1.0)
BuildRequires : pkgconfig(x11)

%description
IBus-Unikey IME
---------------
Author: LÃª Quá»c Tuáº¥n <mr.lequoctuan@gmail.com>
Home: http://ibus-unikey.googlecode.com
License: GNU GENERAL PUBLIC LICENSE v3
---------------------------------------------
ibus-unikey is an ibus input method engine.
It use ukengine for progress key event.
(a modified version of ukengine)

%package data
Summary: data components for the ibus-unikey package.
Group: Data

%description data
data components for the ibus-unikey package.


%package libexec
Summary: libexec components for the ibus-unikey package.
Group: Default
Requires: ibus-unikey-license = %{version}-%{release}

%description libexec
libexec components for the ibus-unikey package.


%package license
Summary: license components for the ibus-unikey package.
Group: Default

%description license
license components for the ibus-unikey package.


%package locales
Summary: locales components for the ibus-unikey package.
Group: Default

%description locales
locales components for the ibus-unikey package.


%prep
%setup -q -n ibus-unikey-0.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559101379
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto -std=gnu++98"
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1559101379
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ibus-unikey
cp COPYING %{buildroot}/usr/share/package-licenses/ibus-unikey/COPYING
cp ukengine/COPYING %{buildroot}/usr/share/package-licenses/ibus-unikey/ukengine_COPYING
%make_install
%find_lang ibus-unikey

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/ibus-unikey/icons/ibus-unikey.png
/usr/share/ibus-unikey/ui/setup-macro.ui
/usr/share/ibus-unikey/ui/setup-main.ui
/usr/share/ibus/component/unikey.xml

%files libexec
%defattr(-,root,root,-)
/usr/libexec/ibus-engine-unikey
/usr/libexec/ibus-setup-unikey

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ibus-unikey/COPYING
/usr/share/package-licenses/ibus-unikey/ukengine_COPYING

%files locales -f ibus-unikey.lang
%defattr(-,root,root,-)

